import { Lead, LeadActivity, PaymentRecord, Reminder, CustomerRecord, UserProfile, ServiceItem, StageChecklist } from '@/types';

export const MOCK_USERS: UserProfile[] = [
  {
    id: 'user_super_admin',
    full_name: 'Dharmikshree',
    phone: '+91 98765 43210',
    whatsapp: '+91 98765 43210',
    role: 'super_admin',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'user_admin_k',
    full_name: 'K (Senior Admin)',
    phone: '+91 98765 43211',
    whatsapp: '+91 98765 43211',
    role: 'admin',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'user_team_n',
    full_name: 'N (Consultation Lead)',
    phone: '+91 98765 43212',
    whatsapp: '+91 98765 43212',
    role: 'team_member',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'user_team_d',
    full_name: 'D (Remedies & Pujas)',
    phone: '+91 98765 43213',
    whatsapp: '+91 98765 43213',
    role: 'team_member',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'user_customer_demo',
    full_name: 'Rajesh Sharma',
    phone: '+91 98200 12345',
    whatsapp: '+91 98200 12345',
    role: 'customer',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-101',
    full_name: 'Rajesh Sharma',
    phone: '+91 98200 12345',
    whatsapp: '+91 98200 12345',
    email: 'rajesh.sharma@example.com',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    lead_source: 'instagram',
    lead_temperature: 'hot',
    service_interest: 'divine_consultation',
    consultation_mode: 'online',
    stage: 'slot_confirmed',
    assigned_to: 'user_team_n',
    assigned_to_user: MOCK_USERS[2],
    date_of_consultation: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    rescheduled: false,
    reschedule_count: 0,
    payment_status: 'full_paid',
    payment_mode: 'upi',
    token_amount: 0,
    full_amount: 9900,
    amount_paid: 9900,
    amount_due: 0,
    protocol_message_sent: true,
    pre_consult_5day_done: true,
    pre_consult_3day_done: false,
    conclusion_notes: '',
    remedy_status: 'not_sent',
    puja_status: 'not_booked',
    stone_status: 'not_decided',
    testimonial_status: 'not_collected',
    internal_notes: 'Urgent consultation for business expansion & Mahadasha shift',
    tags: ['High Value', 'VIP Client'],
    is_converted: true,
    converted_customer_id: 'user_customer_demo',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    created_by: 'user_admin_k',
  },
  {
    id: 'lead-102',
    full_name: 'Priya Patel',
    phone: '+91 98980 54321',
    whatsapp: '+91 98980 54321',
    email: 'priya.patel@example.com',
    city: 'Ahmedabad',
    state: 'Gujarat',
    country: 'India',
    lead_source: 'website',
    lead_temperature: 'hot',
    service_interest: 'vastu_alignment',
    consultation_mode: 'offline',
    stage: 'payment_received',
    assigned_to: 'user_team_n',
    assigned_to_user: MOCK_USERS[2],
    date_of_consultation: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    rescheduled: false,
    reschedule_count: 0,
    payment_status: 'token_paid',
    payment_mode: 'bank_transfer',
    token_amount: 15000,
    full_amount: 72000,
    amount_paid: 15000,
    amount_due: 57000,
    protocol_message_sent: true,
    pre_consult_5day_done: false,
    pre_consult_3day_done: false,
    conclusion_notes: '',
    remedy_status: 'not_sent',
    puja_status: 'not_booked',
    stone_status: 'not_decided',
    testimonial_status: 'not_collected',
    internal_notes: 'Bungalow Vastu in Science City, Ahmedabad',
    tags: ['Vastu Project'],
    is_converted: false,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    created_by: 'user_team_n',
  },
  {
    id: 'lead-103',
    full_name: 'Amitabh Sen',
    phone: '+91 98310 99887',
    whatsapp: '+91 98310 99887',
    email: 'amitabh.sen@example.com',
    city: 'Kolkata',
    state: 'West Bengal',
    country: 'India',
    lead_source: 'youtube',
    lead_temperature: 'warm',
    service_interest: 'business_name_consultation',
    consultation_mode: 'online',
    stage: 'qualified_hot',
    assigned_to: 'user_team_d',
    assigned_to_user: MOCK_USERS[3],
    rescheduled: false,
    reschedule_count: 0,
    payment_status: 'unpaid',
    token_amount: 0,
    full_amount: 18000,
    amount_paid: 0,
    amount_due: 18000,
    protocol_message_sent: false,
    pre_consult_5day_done: false,
    pre_consult_3day_done: false,
    remedy_status: 'not_sent',
    puja_status: 'not_booked',
    stone_status: 'not_decided',
    testimonial_status: 'not_collected',
    internal_notes: 'New D2C startup name guidance',
    tags: ['Startup'],
    is_converted: false,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    created_by: 'user_team_d',
  },
  {
    id: 'lead-104',
    full_name: 'Sunita Rao',
    phone: '+91 98450 77665',
    whatsapp: '+91 98450 77665',
    email: 'sunita.rao@example.com',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    lead_source: 'referral',
    lead_temperature: 'hot',
    service_interest: 'marriage_compatibility',
    consultation_mode: 'online',
    stage: 'consultation_done',
    assigned_to: 'user_team_n',
    assigned_to_user: MOCK_USERS[2],
    date_of_consultation: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    rescheduled: false,
    reschedule_count: 0,
    payment_status: 'full_paid',
    payment_mode: 'upi',
    token_amount: 0,
    full_amount: 7200,
    amount_paid: 7200,
    amount_due: 0,
    protocol_message_sent: true,
    pre_consult_5day_done: true,
    pre_consult_3day_done: true,
    conclusion_notes: 'Kanya Rashi match. Suggested Rahu Shanti Puja & Pearl gemstone.',
    remedy_status: 'sent',
    puja_status: 'booked',
    stone_status: 'dispatched',
    courier_tracking_no: 'BLUE_DART_887910',
    testimonial_status: 'not_collected',
    internal_notes: 'Consultation conducted smoothly. Client satisfied.',
    tags: ['Marriage Match'],
    is_converted: false,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    created_by: 'user_admin_k',
  },
  {
    id: 'lead-105',
    full_name: 'Kavita Singhania',
    phone: '+91 98110 33445',
    whatsapp: '+91 98110 33445',
    email: 'kavita.s@example.com',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    lead_source: 'facebook',
    lead_temperature: 'cold',
    service_interest: 'garbh_sanskar',
    consultation_mode: 'online',
    stage: 'new_lead',
    rescheduled: false,
    reschedule_count: 0,
    payment_status: 'unpaid',
    token_amount: 0,
    full_amount: 7200,
    amount_paid: 0,
    amount_due: 7200,
    protocol_message_sent: false,
    pre_consult_5day_done: false,
    pre_consult_3day_done: false,
    remedy_status: 'not_sent',
    puja_status: 'not_booked',
    stone_status: 'not_decided',
    testimonial_status: 'not_collected',
    internal_notes: 'Inquired via FB form for 2nd trimester guidance',
    tags: ['FB Ad'],
    is_converted: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: 'user_super_admin',
  },
];

export const INITIAL_ACTIVITIES: LeadActivity[] = [
  {
    id: 'act-1',
    lead_id: 'lead-101',
    activity_type: 'system',
    content: 'Lead created via Instagram campaign enquiry form',
    is_internal: true,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-2',
    lead_id: 'lead-101',
    activity_type: 'payment_update',
    content: 'Recorded Full Payment of ₹9,900 via UPI (Ref: UPI/391094101)',
    old_value: 'unpaid',
    new_value: 'full_paid',
    is_internal: true,
    created_by: 'user_admin_k',
    created_by_user: MOCK_USERS[1],
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-3',
    lead_id: 'lead-101',
    activity_type: 'stage_change',
    content: 'Moved lead stage from Payment Received to Slot Confirmed',
    old_value: 'payment_received',
    new_value: 'slot_confirmed',
    is_internal: true,
    created_by: 'user_team_n',
    created_by_user: MOCK_USERS[2],
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-4',
    lead_id: 'lead-104',
    activity_type: 'note',
    content: 'Completed 45-min Zoom consultation. Client requested Mahapuja booking & gemstone recommendation.',
    is_internal: true,
    created_by: 'user_team_n',
    created_by_user: MOCK_USERS[2],
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_REMINDERS: Reminder[] = [
  {
    id: 'rem-1',
    lead_id: 'lead-101',
    lead_name: 'Rajesh Sharma',
    lead_phone: '+91 98200 12345',
    service_name: 'Divine Consultation',
    reminder_type: 'pre_consult_5day',
    scheduled_for: new Date().toISOString(), // Today
    channel: 'whatsapp',
    status: 'pending',
    message_template: 'नमस्ते Rajesh Sharma 🙏 आपकी Divine Consultation 5 दिन बाद scheduled है। — Team Dharmikshree',
    assigned_to: 'user_team_n',
    assigned_to_user: MOCK_USERS[2],
    notes: 'Today due: Send 5-day confirmation message',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rem-2',
    lead_id: 'lead-102',
    lead_name: 'Priya Patel',
    lead_phone: '+91 98980 54321',
    service_name: 'Vastu & Space Alignment',
    reminder_type: 'payment_due',
    scheduled_for: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // Overdue
    channel: 'whatsapp',
    status: 'pending',
    message_template: 'नमस्ते Priya Patel 🙏 Vastu alignment remaining balance ₹57,000 pending. — Team Dharmikshree',
    assigned_to: 'user_team_n',
    assigned_to_user: MOCK_USERS[2],
    notes: 'Payment reminder for remaining Vastu fee',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rem-3',
    lead_id: 'lead-104',
    lead_name: 'Sunita Rao',
    lead_phone: '+91 98450 77665',
    service_name: 'Marriage Compatibility',
    reminder_type: 'stone_followup',
    scheduled_for: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // Upcoming
    channel: 'manual_call',
    status: 'pending',
    message_template: 'Call Sunita Rao regarding Gemstone delivery tracking',
    assigned_to: 'user_team_d',
    assigned_to_user: MOCK_USERS[3],
    notes: 'Verify BlueDart tracking delivery status',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-1',
    lead_id: 'lead-101',
    customer_id: 'user_customer_demo',
    lead_name: 'Rajesh Sharma',
    service: 'Divine Consultation',
    payment_type: 'full',
    amount: 9900,
    payment_mode: 'upi',
    payment_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    reference_no: 'UPI/391094101',
    notes: 'Full payment received via PhonePe',
    recorded_by: 'user_admin_k',
    recorded_by_user: MOCK_USERS[1],
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'pay-2',
    lead_id: 'lead-102',
    lead_name: 'Priya Patel',
    service: 'Vastu & Space Alignment',
    payment_type: 'token',
    amount: 15000,
    payment_mode: 'bank_transfer',
    payment_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    reference_no: 'IMPS/992011287',
    notes: 'Initial token amount for Vastu site visit',
    recorded_by: 'user_team_n',
    recorded_by_user: MOCK_USERS[2],
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'pay-3',
    lead_id: 'lead-104',
    lead_name: 'Sunita Rao',
    service: 'Marriage Compatibility',
    payment_type: 'full',
    amount: 7200,
    payment_mode: 'upi',
    payment_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    reference_no: 'GPAY/771092841',
    notes: 'Kundali match full dakshina',
    recorded_by: 'user_admin_k',
    recorded_by_user: MOCK_USERS[1],
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_CUSTOMERS: CustomerRecord[] = [
  {
    id: 'user_customer_demo',
    lead_id: 'lead-101',
    full_name: 'Rajesh Sharma',
    phone: '+91 98200 12345',
    email: 'rajesh.sharma@example.com',
    city: 'Mumbai',
    customer_since: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    total_spent: 27900,
    total_sessions: 2,
    notes: 'Valued client, recurring consultation for business growth',
    tags: ['VIP Client', 'Dharmikshree Preferred'],
  },
];
